name: CI/CD LAMP Docker

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v3

      - name: Build des containers
        run: docker compose -f docker-compose.yml build

      - name: Test local du container
        run: |
          docker compose -f docker-compose.yml up -d
          sleep 15
          curl -f http://localhost:8080 || exit 1
          docker compose down

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Récupération du code
        uses: actions/checkout@v3

      - name: Config SSH
        run: |
          mkdir -p ~/.ssh
          # Création du fichier de clé privée en conservant exactement les retours à la ligne
          cat <<'EOF' > ~/.ssh/id_rsa
${{ secrets.VPS_SSH_KEY }}
EOF
          chmod 600 ~/.ssh/id_rsa
          # Ajouter l'hôte EC2 à known_hosts pour éviter les prompts
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Déploiement sur le VPS
        run: |
          # Synchroniser le code avec le serveur EC2
          rsync -avz --exclude '.git' ./ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:~/lamp-app
          # Lancer les containers sur EC2
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "cd ~/lamp-app && docker compose pull && docker compose up -d --build"
